cmake_minimum_required(VERSION 3.20)

if (NOT DEFINED PROJECT_SOURCE_DIR)
    message(FATAL_ERROR "PROJECT_SOURCE_DIR is required")
endif()

set(SRC_CMAKE "${PROJECT_SOURCE_DIR}/src/CMakeLists.txt")
set(VCXPROJ "${PROJECT_SOURCE_DIR}/vc18/theforgottenserver.vcxproj")

foreach(required_file IN ITEMS "${SRC_CMAKE}" "${VCXPROJ}")
    if (NOT EXISTS "${required_file}")
        message(FATAL_ERROR "Required file does not exist: ${required_file}")
    endif()
endforeach()

file(READ "${SRC_CMAKE}" cmake_sources)
file(READ "${VCXPROJ}" vcxproj_sources)

string(REGEX MATCHALL "\\$\\{CMAKE_CURRENT_LIST_DIR\\}/[^ \t\r\n\\)]+\\.(cpp|h)" cmake_entries "${cmake_sources}")
set(cmake_files)
foreach(entry IN LISTS cmake_entries)
    string(REPLACE "\${CMAKE_CURRENT_LIST_DIR}/" "" file_name "${entry}")
    list(APPEND cmake_files "${file_name}")
endforeach()
list(APPEND cmake_files "main.cpp")
list(REMOVE_DUPLICATES cmake_files)
list(SORT cmake_files)

string(REGEX MATCHALL "<Cl(Compile|Include) Include=\"\\.\\.\\\\src\\\\[^\"]+\\.(cpp|h)\"" vcxproj_entries "${vcxproj_sources}")
set(vcxproj_files)
foreach(entry IN LISTS vcxproj_entries)
    string(REGEX REPLACE "^<Cl(Compile|Include) Include=\"\\.\\.\\\\src\\\\" "" file_name "${entry}")
    string(REGEX REPLACE "\"$" "" file_name "${file_name}")
    string(REPLACE "\\" "/" file_name "${file_name}")
    list(APPEND vcxproj_files "${file_name}")
endforeach()
list(REMOVE_DUPLICATES vcxproj_files)
list(SORT vcxproj_files)

set(missing_from_vcxproj)
foreach(file_name IN LISTS cmake_files)
    if (NOT file_name IN_LIST vcxproj_files)
        list(APPEND missing_from_vcxproj "${file_name}")
    endif()
endforeach()

set(missing_from_cmake)
foreach(file_name IN LISTS vcxproj_files)
    if (NOT file_name IN_LIST cmake_files)
        list(APPEND missing_from_cmake "${file_name}")
    endif()
endforeach()

if (missing_from_vcxproj OR missing_from_cmake)
    if (missing_from_vcxproj)
        list(JOIN missing_from_vcxproj ", " missing_from_vcxproj_text)
        message(SEND_ERROR "Files in src/CMakeLists.txt but missing from vc18/theforgottenserver.vcxproj: ${missing_from_vcxproj_text}")
    endif()
    if (missing_from_cmake)
        list(JOIN missing_from_cmake ", " missing_from_cmake_text)
        message(SEND_ERROR "Files in vc18/theforgottenserver.vcxproj but missing from src/CMakeLists.txt: ${missing_from_cmake_text}")
    endif()
    message(FATAL_ERROR "CMake and Visual Studio source lists are out of sync")
endif()

message(STATUS "CMake and Visual Studio source lists are in sync")
